id: P010543
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:10.518366
source_metadata:
  id: bdr:W1KG24835
  title: ལུང་རྟོགས་ཀྱི་འབེལ་གཏམ་ཉུང་ངུ་།
  author: ''
  volumes:
    5adcaea19a634bc389b556d6920f5d46:
      image_group_id: I1KG24837
      title: ''
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
