id: IA090777D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:14:12+00:00'
last_modified: '2022-06-08T14:22:38.262731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24835
  title: ལུང་རྟོགས་ཀྱི་འབེལ་གཏམ་ཉུང་ངུ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '7373':
      image_group_id: I1KG24837
      title: ''
      total_pages: 135
      order: 1
      base_file: 7373.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
